[package]
name = "wasapi-literal"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58.0", features = [
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_System_Performance"
]}